# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# Run this test only, when a toolchain for java 11 is available
invoker.toolchain.jdk.version = 11

# The jdk toolchain "11" is selected in pom.xml.
# With this toolchain configuration, PmdExecutor will be called with Java 11.
# While maven3 and PMD 7 still require only java 8 as the minimum,
# maven4 requires Java 17+.
# Therefore, the PmdExecutor must not use any classes from Maven
# directly, otherwise UnsupportedClassVersionErrors are thrown.

invoker.goals = clean verify
